apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
<<<<<<< Updated upstream
  # - secrets.yaml
  - infra.yaml
  - primary-infra.yaml
  - pri-infra.yaml
  # - app-repo.yaml
  # - customer-a.yaml
  # - customer-b.yaml
  # - sachin.yaml
=======
  - secrets.yaml
  # - infra.yaml
  # - primary-infra.yaml
  # - pri-infra.yaml
  - app-repo.yaml
  - customer-a.yaml
  - customer-b.yaml
  - sachin.yaml
>>>>>>> Stashed changes
  
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ${product}-${locationShort}-${environment}-env-vars
  envs:
  - .env
