apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
     # - secrets.yaml
                 # - infra.yaml
                     # - primary-infra.yaml
     # - pri-infra.yaml
                # - app-repo.yaml
     # - customer-a.yaml
 #  - sachin.yaml
   #   - customer-b.yaml
  
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ${product}-${locationShort}-${environment}-env-vars
  envs:
  - .env
