apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- secrets.yaml
  #- infra.yaml
  #- app.yaml
  
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ${product}-${locationShort}-${environment}-env-vars
  envs:
  - .env
