name: Scheduled Comments on File

on:
  schedule:
    - cron: "30 13 * * 6" # First schedule for 'hello3'
    - cron: "0 14 * * 6"  # Second schedule for 'hello4'
  workflow_dispatch:

jobs:
  comment-hello3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug:Show file content before commenting 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Raw file content before commenting 'hello3':"
          cat "$FILE"

      - name: Detect and Comment 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          if grep -q '^# *hello3' "$FILE"; then
            echo "'hello3' is already commented. Skipping..."
          else
            echo "Commenting 'hello3'."
            sed -i '/hello3/s/^/# /' "$FILE"
          fi

      - name: Debug:Show file content after commenting 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "File content after commenting 'hello3':"
          cat "$FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Commented 'hello3'" || echo "No changes to commit"
          git push origin main

  comment-hello4:
    needs: comment-hello3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug:Show file content before commenting 'hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Raw file content before commenting 'hello4':"
          cat "$FILE"

      - name: Detect and Comment 'hello4' if 'hello3' is commented
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          if grep -q '^# *hello3' "$FILE"; then
            echo "'hello3' is commented. Proceeding to comment 'hello4'."
            if grep -q '^# *hello4' "$FILE"; then
              echo "'hello4' is already commented. Skipping..."
            else
              echo "Commenting 'hello4'."
              sed -i '/hello4/s/^/# /' "$FILE"
            fi
          else
            echo "'hello3' is not commented. Skipping 'hello4'."
          fi

      - name: Debug:Show file content after commenting 'hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "File content after commenting 'hello4':"
          cat "$FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Commented 'hello4'" || echo "No changes to commit"
          git push origin main
