name: Scheduled Comments on File

on:
  schedule:
    - cron: "30 7 * * 0" # Single schedule at 1:00 PM IST on Sunday
  workflow_dispatch: # Allows manual trigger

jobs:
  comment-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run 'comment-hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Running job 'comment-hello3' at $(date)"
          if grep -q '^# *hello3' "$FILE"; then
            echo "'hello3' is already commented. Skipping..."
          else
            echo "Commenting 'hello3'."
            sed -i '/hello3/s/^/# /' "$FILE"
          fi
        id: comment-hello3

      - name: Commit and push changes for 'hello3'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Commented 'hello3'" || echo "No changes to commit"
          git push origin main

      - name: Wait for 30 minutes
        run: sleep 1800 # 30 minutes in seconds

      - name: Run 'comment-hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Running job 'comment-hello4' at $(date)"
          if grep -q '^# *hello4' "$FILE"; then
            echo "'hello4' is already commented. Skipping..."
          else
            echo "Commenting 'hello4'."
            sed -i '/hello4/s/^/# /' "$FILE"
          fi

      - name: Commit and push changes for 'hello4'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Commented 'hello4'" || echo "No changes to commit"
          git push origin main
