name: Scheduled Uncomments on File

on:
  schedule:
    - cron: "0 9 * * 0" # Single schedule at 2:30 PM IST on Sunday
  workflow_dispatch: # Allows manual trigger

jobs:
  uncomment-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run 'uncomment-hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Running job 'uncomment-hello4' at $(date)"
          if grep -q '^# *hello4' "$FILE"; then
            echo "Uncommenting 'hello4'."
            sed -i '/# *hello4/s/^# *//' "$FILE"
          else
            echo "'hello4' is already uncommented. Skipping..."
          fi
        id: uncomment-hello4

      - name: Commit and push changes for 'hello4'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Uncommented 'hello4'" || echo "No changes to commit"
          git push origin main

      - name: Wait for 30 minutes
        run: sleep 60 # 30 minutes in seconds

      - name: Run 'uncomment-hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Running job 'uncomment-hello3' at $(date)"
          if grep -q '^# *hello3' "$FILE"; then
            echo "Uncommenting 'hello3'."
            sed -i '/# *hello3/s/^# *//' "$FILE"
          else
            echo "'hello3' is already uncommented. Skipping..."
          fi

      - name: Commit and push changes for 'hello3'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add example.txt
          git commit -m "Uncommented 'hello3'" || echo "No changes to commit"
          git push origin main
