name: Scheduled Comments on File

on:
  schedule:
    # Schedule for every Saturday
    - cron: "30 13 * * 6" # 7 PM IST for 'hello3'
    - cron: "0 14 * * 6"  # 7:30 PM IST for 'hello4'
  workflow_dispatch:

jobs:
  comment-hello3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:Show file content before commenting 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Raw file content before commenting 'hello3':"
          cat "$FILE"

      - name: Comment 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          if grep -q '^# hello3' "$FILE" || grep -q '^#hello3' "$FILE"; then
            echo "'hello3' is already commented. Skipping..."
          else
            echo "Commenting 'hello3'."
            sed -i '/hello3/s/^/# /' "$FILE"
          fi

      - name: Debug:Show file content after commenting 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "File content after commenting 'hello3':"
          cat "$FILE"

      - name: Commit and push changes for 'hello3'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add "$FILE"
          git commit -m "Automated update: Commented 'hello3'" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main || echo "No changes to push"

  comment-hello4:
    needs: comment-hello3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:Show file content before commenting 'hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "Raw file content before commenting 'hello4':"
          cat "$FILE"

      - name: Comment 'hello4' if 'hello3' is commented
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          if grep -q '^# hello3' "$FILE" || grep -q '^#hello3' "$FILE"; then
            echo "'hello3' is commented. Proceeding to comment 'hello4'."
            sed -i '/hello4/s/^/# /' "$FILE"
          else
            echo "'hello3' is not commented. Skipping 'hello4'."
          fi

      - name: Debug:Show file content after commenting 'hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "File content after commenting 'hello4':"
          cat "$FILE"

      - name: Commit and push changes for 'hello4'
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add "$FILE"
          git commit -m "Automated update: Commented 'hello4'" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main || echo "No changes to push"
