name: Scheduled Comments Dynamically

on:
  schedule:
    - cron: "30 7 * * 0" # Every Sunday at 1:00 PM IST
  workflow_dispatch:

jobs:
  comment-dynamic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run 'comment-non-infra'
        run: |
          FILE="$GITHUB_WORKSPACE/dynamicfile.yml"
          echo "Running job 'comment-non-infra' at $(date)"
          echo "Commenting all .yaml files that do NOT contain 'infra'"
          awk '
            BEGIN { in_resources=0 }
            /^resources:/ { in_resources=1; print; next }
            in_resources && /^  - .*\.yaml/ {
              if ($0 ~ /infra/) {
                print
              } else {
                print "  #"$0
              }
              next
            }
            { print }
          ' "$FILE" > temp.yml && mv temp.yml "$FILE"
        id: comment-non-infra

      - name: Commit and push changes for 'comment-non-infra'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dynamicfile.yml
          git commit -m "Commented non-infra .yaml files" || echo "No changes to commit"
          git push origin main

      - name: Wait for 60 seconds
        run: sleep 60

      - name: Run 'comment-infra'
        run: |
          FILE="$GITHUB_WORKSPACE/dynamicfile.yml"
          echo "Running job 'comment-infra' at $(date)"
          echo "Commenting all .yaml files that DO contain 'infra'"
          awk '
            BEGIN { in_resources=0 }
            /^resources:/ { in_resources=1; print; next }
            in_resources && /^  - .*infra.*\.yaml/ {
              print "  #"$0
              next
            }
            { print }
          ' "$FILE" > temp.yml && mv temp.yml "$FILE"
        id: comment-infra

      - name: Commit and push changes for 'comment-infra'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dynamicfile.yml
          git commit -m "Commented infra .yaml files" || echo "No changes to commit"
          git pull origin main --rebase || echo "No remote changes to rebase"
          git push origin main
