name: Comment and Uncomment Lines

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: '30 14 * * 5'  # Friday 8 PM IST (2:30 PM UTC)
    - cron: '30 2 * * 1'   # Monday 8 AM IST (2:30 AM UTC)

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:List Files and Directories
        run: ls -R $GITHUB_WORKSPACE

      - name: Debug:Check FILE variable
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "FILE path is: $FILE"
          if [ ! -f "$FILE" ]; then
            echo "Error: File not found at $FILE"
            exit 1
          fi

      - name: Modify file based on day
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          DAY=$(date +%u)  # Get current day of the week (1=Monday, 5=Friday)

          if [ "$DAY" -eq 5 ]; then
            echo "It's Friday evening. Commenting lines..."
            sed -i '2s/^/# /' "$FILE"
            sed -i '3s/^/# /' "$FILE"
          elif [ "$DAY" -eq 1 ]; then
            echo "It's Monday morning. Uncommenting lines..."
            sed -i '3s/^# //' "$FILE"
            sed -i '2s/^# //' "$FILE"
          fi

      - name: Debug:Check file content after sed
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          echo "File content after modification:"
          cat "$FILE"

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          FILE="$GITHUB_WORKSPACE/example.txt"
          git add "$FILE"
          git commit -m "Automated update for line 2 and 3 based on schedule" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main || echo "No changes to push"
