name: Comment and Uncomment Lines

on:
  workflow_dispatch:  # Enable manual trigger

jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:Print simulated day
        run: |
          DAY=5  # Simulate Friday for testing
          echo "Simulated day is $DAY"

      - name: Set up file path
        run: |
          FILE="$GITHUB_WORKSPACE/Demo1/example.txt"
          echo "Using file at $FILE"

      - name: Debug:Check file content before sed
        run: |
          FILE="$GITHUB_WORKSPACE/Demo1/example.txt"
          echo "File content before modification:"
          cat "$FILE"

      - name: Modify file based on simulated day
        run: |
          FILE="$GITHUB_WORKSPACE/Demo1/example.txt"
          DAY=5  # Simulate Friday for testing
          if [ "$DAY" -eq 5 ]; then
            echo "It's Friday evening. Commenting lines..."
            sed -i '2s/^/# /' "$FILE"
            sed -i '3s/^/# /' "$FILE"
          elif [ "$DAY" -eq 1 ]; then
            echo "It's Monday morning. Uncommenting lines..."
            sed -i '3s/^# //' "$FILE"
            sed -i '2s/^# //' "$FILE"
          fi

      - name: Debug: Check file content after sed
        run: |
          FILE="$GITHUB_WORKSPACE/Demo1/example.txt"
          echo "File content after modification:"
          cat "$FILE"

      - name: Commit and push changes
        run: |
          FILE="$GITHUB_WORKSPACE/Demo1/example.txt"
          git add "$FILE"
          git commit -m "Automated update for line 2 and 3 based on schedule" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main || echo "No changes to push"
