name: Comment and Uncomment Lines

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: '30 14 * * 5'  # Friday 8 PM IST (2:30 PM UTC)
    - cron: '30 2 * * 1'   # Monda
jobs:
  modify-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Modify file based on day
        run: |
          DAY=5  # Simulate Friday for testing
          FILE="example.txt"

          if [ "$DAY" -eq 5 ]; then
            echo "It's Friday evening. Commenting lines..."
            sed -i '2s/^/# /' $FILE
            git add $FILE
            git commit -m "Commented line 2"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sachin-mandal-spm/Demo1.git

            echo "Waiting 10 seconds before commenting line 3..."
            sleep 10

            sed -i '3s/^/# /' $FILE
            git add $FILE
            git commit -m "Commented line 3"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sachin-mandal-spm/Demo1.git

          elif [ "$DAY" -eq 1 ]; then
            echo "It's Monday morning. Uncommenting line 3..."
            sed -i '3s/^# //' $FILE
            git add $FILE
            git commit -m "Uncommented line 3"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sachin-mandal-spm/Demo1.git

            echo "Waiting 10 seconds before uncommenting line 2..."
            sleep 10

            sed -i '2s/^# //' $FILE
            git add $FILE
            git commit -m "Uncommented line 2"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sachin-mandal-spm/Demo1.git
