name: Scheduled Comments Dynamically

on:
  schedule:
    - cron: "0 7 * * 2" # Every Tuesday at 12:30 PM IST
  workflow_dispatch:

jobs:
  comment-dynamic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: branch1

      - name: Run 'comment-non-infra'
        run: |
          FILE="$GITHUB_WORKSPACE/dynamicfile.yml"
          echo "Running job 'comment-non-infra' at $(date)"
          echo "Commenting all .yaml files that do NOT contain 'infra' AND contain 'customer' OR 'app'"
          awk '
            BEGIN { in_resources=0 }
            /^[[:space:]]*resources:/ { in_resources=1; print; next }
            in_resources && /^[[:space:]]*[-#][[:space:]]*-?[[:space:]]*.*\.yaml/ {
              if ($0 ~ /infra/) {
                print
              } else if (($0 ~ /customer/ || $0 ~ /app/) && $0 !~ /^[[:space:]]*#/) {
                print gensub(/^([[:space:]]*)-/, "\\1# -", 1)
              } else {
                print
              }
              next
            }
            { print }
          ' "$FILE" > temp.yml && mv temp.yml "$FILE"
        id: comment-non-infra

      - name: Commit and push changes for 'comment-non-infra'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dynamicfile.yml
          git commit -m "Commented non-infra .yaml files with customer or app" || echo "No changes to commit"
          git push origin branch1

      - name: Wait for 60 seconds
        run: sleep 60

      - name: Run 'comment-infra'
        run: |
          FILE="$GITHUB_WORKSPACE/dynamicfile.yml"
          echo "Running job 'comment-infra' at $(date)"
          echo "Commenting all .yaml files that DO contain 'infra'"
          awk '
            BEGIN { in_resources=0 }
            /^[[:space:]]*resources:/ { in_resources=1; print; next }
            in_resources && $0 ~ /infra.*\.yaml/ {
              if ($0 !~ /^[[:space:]]*#/) {
                print gensub(/^([[:space:]]*)-/, "\\1# -", 1)
              } else {
                print
              }
              next
            }
            { print }
          ' "$FILE" > temp.yml && mv temp.yml "$FILE"
        id: comment-infra

      - name: Commit and push changes for 'comment-infra'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dynamicfile.yml
          git commit -m "Commented infra .yaml files" || echo "No changes to commit"
          git push origin branch1
